<a href="https://colab.research.google.com/github/GTD2101-ACD-GB-EJ25/02-Python-intermedio-ricardo-qm/blob/main/02.%20IndSelAss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Indexando, Seleccionando y Asignando datos

En este JNB se revisará el tema de Indexamiento, Selección y Asignación de datos en Pandas

In [1]:
import pandas as pd
reviews = pd.read_csv("https://raw.githubusercontent.com/GTD2101-ACD-GB-EJ25/ACD.datasets.kaggle/refs/heads/main/winemag-data-130k-v2.txt", index_col=0)
pd.set_option('display.max_rows', 5)

In [2]:
reviews

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [3]:
reviews.country

0            Italy
1         Portugal
            ...
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [4]:
type(reviews.country)

pandas.core.series.Series

In [5]:
reviews['country']

0            Italy
1         Portugal
            ...
129969      France
129970      France
Name: country, Length: 129971, dtype: object

In [6]:
type(reviews['country'])

pandas.core.series.Series

In [7]:
reviews['country'][0]

'Italy'

In [8]:
reviews.iloc[0]

country                                                    Italy
description    Aromas include tropical fruit, broom, brimston...
                                     ...
variety                                              White Blend
winery                                                   Nicosia
Name: 0, Length: 13, dtype: object

In [9]:
type(reviews.iloc[0])

pandas.core.series.Series

In [10]:
reviews.iloc[:, 0]

0            Italy
1         Portugal
            ...
129969      France
129970      France
Name: country, Length: 129971, dtype: object